# Step 1. Build fat jar
FROM gradle:8.10-jdk17 AS build

WORKDIR /home/gradle/src

COPY build.gradle settings.gradle gradlew ./
COPY gradle ./gradle
COPY src ./src

# Build fat JAR
RUN gradle botFatJar --no-daemon

# Step 2. Light image for running the bot
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app
COPY --from=build /home/gradle/src/build/libs/bot.jar /app/bot.jar

ENV DISCORD_BOT_TOKEN=""

ENTRYPOINT ["java", "-jar", "/app/bot.jar"]